{{- if .Values.advancedFabric.enabled }}
apiVersion: {{ .Values.advancedFabric.apiGroup }}/v1alpha1
kind: AdvancedFabric
metadata: {name: {{ .Values.advancedFabric.instanceName }}}
spec:
{{ toYaml (omit .Values.advancedFabric "enabled" "instanceName" "runtimeNamespace" "apiGroup" "legacyApiGroup") | indent 2 }}
{{- end }}
